<?php

/*
|--------------------------------------------------------------------------
| Conteúdo do portfólio
|--------------------------------------------------------------------------
|
| Todos os dados abaixo foram levantados a partir dos repositórios públicos
| de github.com/Mrcidele (READMEs, código-fonte e metadados do GitHub).
| Para adicionar um projeto, basta incluir um novo item em "projects".
|
*/

return [

    'profile' => [
        'name' => 'Caio Tsutiya Marcidele',
        'short_name' => 'Caio Marcidele',
        'username' => 'Mrcidele',
        'github' => 'https://github.com/Mrcidele',
        'avatar' => 'https://avatars.githubusercontent.com/u/160981343?v=4',
        'role' => 'Desenvolvedor de Software · Back-end & Web',
        'headline' => 'Construo APIs REST, sistemas web em PHP/Laravel e aplicações com arquitetura limpa, testes automatizados e Docker.',
        'about' => [
            'Sou desenvolvedor com foco em back-end. No GitHub desde 2024, meus repositórios contam a evolução de quem começou com APIs em C# e chegou a sistemas web completos em PHP e Laravel — passando por front-end com Next.js, apps Android em Kotlin e muitos padrões de projeto em Java.',
            'Boa parte do que está aqui nasceu de disciplinas da faculdade — provas, trabalhos finais e exercícios — e eu trato cada um como produto: camadas bem separadas, regras de negócio isoladas em services, validação, testes com PHPUnit e ambiente replicável com Docker.',
        ],
        'github_since' => '2024-02',
        'public_repos' => 40,
    ],

    'focus' => [
        [
            'icon' => 'api',
            'title' => 'APIs REST',
            'text' => 'Endpoints bem definidos em Laravel, Express e ASP.NET Core, com integração a serviços externos como ViaCEP e wttr.in.',
        ],
        [
            'icon' => 'shield',
            'title' => 'Web segura com PHP',
            'text' => 'MVC e Clean Architecture com DTOs, CSRF, rate limiting, Argon2id, CSP e auditoria imutável.',
        ],
        [
            'icon' => 'layers',
            'title' => 'Arquitetura & Padrões',
            'text' => 'Padrões GoF aplicados em Java — Strategy, State, Adapter, Chain of Responsibility e outros — com foco em SOLID.',
        ],
        [
            'icon' => 'device',
            'title' => 'Front-end & Mobile',
            'text' => 'Interfaces em Next.js + TypeScript consumindo APIs e apps Android com Kotlin, Jetpack Compose e Firebase.',
        ],
    ],

    'skills' => [
        'Back-end' => ['PHP', 'Laravel', 'C#', 'ASP.NET Core', 'Node.js', 'Express', 'Python', 'Django', 'Java'],
        'Front-end' => ['TypeScript', 'JavaScript', 'Vue.js', 'React', 'Next.js', 'Blade', 'HTML', 'CSS'],
        'Mobile' => ['Kotlin', 'Jetpack Compose', 'Firebase'],
        'Dados & Infra' => ['PostgreSQL', 'MySQL', 'SQLite', 'Redis', 'Entity Framework', 'PDO', 'Docker', 'GitHub Actions', 'PHPUnit', 'Pest', 'Swagger'],
    ],

    // Ícones do Devicon (https://devicon.dev, licença MIT) em public/images/tech.
    'tech_icons' => [
        'PHP' => 'php-original.svg',
        'Laravel' => 'laravel-original.svg',
        'C#' => 'csharp-original.svg',
        'ASP.NET Core' => 'dotnetcore-original.svg',
        'Node.js' => 'nodejs-original.svg',
        'Express' => 'express-original.svg',
        'Python' => 'python-original.svg',
        'Django' => 'django-plain.svg',
        'Java' => 'java-original.svg',
        'TypeScript' => 'typescript-original.svg',
        'JavaScript' => 'javascript-original.svg',
        'React' => 'react-original.svg',
        'Vue.js' => 'vuejs-original.svg',
        'Next.js' => 'nextjs-original.svg',
        'HTML' => 'html5-original.svg',
        'CSS' => 'css3-original.svg',
        'Kotlin' => 'kotlin-original.svg',
        'Jetpack Compose' => 'jetpackcompose-original.svg',
        'Firebase' => 'firebase-original.svg',
        'PostgreSQL' => 'postgresql-original.svg',
        'MySQL' => 'mysql-original.svg',
        'Redis' => 'redis-original.svg',
        'SQLite' => 'sqlite-original.svg',
        'Docker' => 'docker-original.svg',
        'GitHub Actions' => 'githubactions-original.svg',
        'Swagger' => 'swagger-original.svg',
    ],

    // Cores oficiais do GitHub Linguist.
    'languages' => [
        'PHP' => '#4F5D95',
        'Python' => '#3572A5',
        'JavaScript' => '#f1e05a',
        'TypeScript' => '#3178c6',
        'C#' => '#178600',
        'Java' => '#b07219',
        'Kotlin' => '#A97BFF',
    ],

    'categories' => [
        'php' => 'PHP & Laravel',
        'js' => 'JavaScript & TS',
        'dotnet' => 'C# & .NET',
        'java' => 'Java & Padrões',
        'mobile' => 'Kotlin & Android',
        'python' => 'Python',
    ],

    'patterns' => [
        ['name' => 'Strategy', 'repos' => ['Strategy', 'prova2', 'provasemestre', 'seatlock', 'forja']],
        ['name' => 'State', 'repos' => ['State', 'prova2']],
        ['name' => 'Adapter', 'repos' => ['Adapter', 'prova2']],
        ['name' => 'Chain of Responsibility', 'repos' => ['Chain', 'prova2', 'forja']],
        ['name' => 'Command', 'repos' => ['prova2']],
        ['name' => 'Factory Method', 'repos' => ['Tarefa1', 'provasemestre', 'Prova-Projeto']],
        ['name' => 'Singleton', 'repos' => ['Tarefa']],
        ['name' => 'Observer', 'repos' => ['Prova-Projeto', 'forja']],
        ['name' => 'Decorator', 'repos' => ['Prova-Projeto', 'seatlock']],
        ['name' => 'Repository', 'repos' => ['MVC_site', 'novo', 'ProvaDSV', 'forja']],
        ['name' => 'Data Mapper', 'repos' => ['forja']],
        ['name' => 'Front Controller', 'repos' => ['MVC_site', 'forja']],
        ['name' => 'DTO', 'repos' => ['MVC_site', 'forja']],
        ['name' => 'Value Object', 'repos' => ['seatlock']],
        ['name' => 'Idempotency Key', 'repos' => ['seatlock']],
        ['name' => 'MVC', 'repos' => ['MVC_site', 'delivery_api_facul', 'delivery-api']],
    ],

    'timeline' => [
        [
            'date' => '2025-04',
            'title' => 'Primeiras APIs em C#',
            'text' => 'APIs com ASP.NET Core e Entity Framework: eventos, catálogo de filmes em equipe e o primeiro contato com migrations e repositórios.',
            'repos' => ['ProvaDSV', 'prova', 'API-STREAMER'],
        ],
        [
            'date' => '2025-06',
            'title' => 'Front-end com Next.js',
            'text' => 'Interfaces em Next.js 15 + TypeScript consumindo APIs próprias e públicas, além de uma API .NET com controle de permissões.',
            'repos' => ['ProvaA1', 'revisao_paises_front', 'f', 'novo'],
        ],
        [
            'date' => '2025-09',
            'title' => 'Android & orientação a objetos',
            'text' => 'Primeiro app em Kotlin com Jetpack Compose e exercícios de POO em Java com herança, interfaces e polimorfismo.',
            'repos' => ['ToDoList', 'Tarefa-2', 'Tarefa1'],
        ],
        [
            'date' => '2025-10',
            'title' => 'Padrões de projeto',
            'text' => 'Uma sequência de implementações GoF em Java — Adapter, Strategy, State, Chain of Responsibility — e o CalendarioApp com MVVM e Firestore.',
            'repos' => ['Adapter', 'Strategy', 'State', 'Chain', 'prova2', 'estudar'],
        ],
        [
            'date' => '2026-02',
            'title' => 'IT Asset Tracker',
            'text' => 'API para controle de equipamentos de TI e empréstimos com ASP.NET Core, EF Core, SQLite e Swagger.',
            'repos' => ['ITAssetTracker'],
        ],
        [
            'date' => '2026-04',
            'title' => 'Node.js e PHP com Docker',
            'text' => 'APIs em Express consumindo ViaCEP e wttr.in e um CRUD em PHP 8.4 + MySQL com auditoria granular rodando em Docker.',
            'repos' => ['api-consumo', 'delivery-api', 'tarefa-api', 'site-php'],
        ],
        [
            'date' => '2026-05',
            'title' => 'Clean Architecture em PHP',
            'text' => 'MVC_site: front controller, DTOs, services, repositories e uma camada de segurança inspirada em práticas de Blue Team.',
            'repos' => ['MVC_site'],
        ],
        [
            'date' => '2026-06',
            'title' => 'Laravel',
            'text' => 'API de delivery em Laravel com integração ViaCEP, regras de frete e testes PHPUnit — e contribuições em um app PHP via fork.',
            'repos' => ['delivery_api_facul', 'fork-Pfeifer'],
        ],
        [
            'date' => '2026-09',
            'title' => 'Django',
            'text' => 'Gerenciador de tarefas estilo Trello em Django, com autenticação, permissões, dashboard e 24 testes automatizados.',
            'repos' => ['Sistema-de-gerenciamento-de-tarefas-web'],
        ],
        [
            'date' => '2026-10',
            'title' => 'Arquitetura avançada em PHP',
            'text' => 'SeatLock, com reserva de assentos por trecho e garantia contra venda dupla testada com processos concorrentes; Forja, um framework PHP 8.4 sobre as PSRs; e a fundação do Tenantly, um SaaS multi-tenant.',
            'repos' => ['seatlock', 'forja', 'tenantly'],
        ],
    ],

    'projects' => [

        [
            'slug' => 'seatlock',
            'name' => 'SeatLock',
            'repo' => 'seatlock',
            'language' => 'PHP',
            'category' => 'php',
            'date' => '2026-10',
            'featured' => true,
            'summary' => 'Venda de passagens rodoviárias em Laravel 13 com reserva de assentos por trecho e garantia contra venda dupla.',
            'description' => 'API e SPA para venda de passagens de ônibus em que cada assento é reservado por segmento da viagem, o que permite vender o mesmo lugar em trechos que não se sobrepõem. O princípio central é que o banco é a fonte da verdade e o Redis é só otimização: locks temporários com scripts Lua melhoram a experiência de compra, mas a garantia final contra venda dupla é um UNIQUE no PostgreSQL, e quem perde a disputa já tendo pago recebe estorno automático. A API cobre o ciclo completo, da busca e do checkout com Pix ou cartão até o bilhete assinado, a validação no embarque e o cancelamento.',
            'stack' => ['PHP 8.4', 'Laravel 13', 'PostgreSQL 17', 'Redis 7', 'Octane (FrankenPHP)', 'Reverb', 'Vue 3 + TypeScript', 'Pest', 'Docker'],
            'highlights' => [
                'Garantia contra venda dupla via UNIQUE(trip_id, seat_id, segment_index) na tabela seat_segments do PostgreSQL.',
                'Lock temporário no Redis com scripts Lua atômicos: trava todos os assentos ou nenhum, e só o dono libera ou renova.',
                'Reserva por trecho: o mesmo assento pode ser vendido para A→B e B→C, já que os segmentos não se sobrepõem.',
                'Decorator fail-open: se o Redis cair, a venda continua e o pagamento que perder no UNIQUE é estornado automaticamente.',
                'Idempotency-Key em pedidos e pagamentos, webhooks deduplicados por UNIQUE(provider, event_id) e status monotônico.',
                'Teste com 12 processos PHP reais disputando o mesmo assento, com Redis e simulando Redis fora: um único vencedor.',
                'Pós-venda: bilhete em PDF com QR assinado (HMAC-SHA256), embarque de uso único, reembolso por antecedência e remarcação.',
            ],
            'endpoints' => [
                ['GET', '/api/v1/trips', 'Busca viagens por cidade de origem, destino e data'],
                ['GET', '/api/v1/trips/{trip}/seat-map', 'Mapa de assentos do trecho: vendidos vêm do banco, travados vêm do Redis'],
                ['POST', '/api/v1/trips/{trip}/locks', 'Trava os assentos para o carrinho (tudo ou nada)'],
                ['POST', '/api/v1/orders', 'Cria pedido pendente para assentos travados (exige Idempotency-Key)'],
                ['POST', '/api/v1/orders/{order}/payments', 'Paga com Pix (BR Code) ou cartão tokenizado (exige Idempotency-Key)'],
                ['POST', '/api/v1/webhooks/{provider}', 'Recebe webhook assinado, grava o evento e processa na fila'],
                ['POST', '/api/v1/orders/{order}/cancel', 'Cancela o pedido; se pago, estorna conforme a antecedência'],
                ['POST', '/api/v1/boarding/validate', 'Valida o QR do bilhete no embarque, uso único (operadores ou admins)'],
            ],
            'flow_title' => 'Fluxo de compra',
            'flow' => [
                ['SeatLockController + LockSeats', 'Checa vendidos no banco e pede o lock'],
                ['RedisSeatLockService', 'Script Lua com SET NX EX por segmento, tudo ou nada'],
                ['EnsureIdempotency + CreateOrder', 'Pedido Pending com o prazo do lock e job de expiração'],
                ['StartPayment + PaymentGatewayManager', 'Cobrança no gateway (Fake, Mercado Pago ou Stripe)'],
                ['IngestWebhook + ProcessWebhookEvent', 'Grava evento único e processa na fila'],
                ['ApplyPaymentStatus', 'Transição monotônica (resposta síncrona ou webhook)'],
                ['ConfirmOrder', 'FOR UPDATE + savepoint em seat_segments; conflito gera estorno'],
                ['SeatSold (Reverb)', 'Broadcast no canal trip.{id} após o commit'],
            ],
        ],

        [
            'slug' => 'forja',
            'name' => 'Forja',
            'repo' => 'forja',
            'language' => 'PHP',
            'category' => 'php',
            'date' => '2026-10',
            'featured' => true,
            'summary' => 'Framework PHP 8.4 construído do zero sobre as PSRs, com container, router por atributos, ORM Data Mapper e worker mode.',
            'description' => 'Framework minimalista com container (PSR-11), pipeline de middleware (PSR-15), eventos (PSR-14), logger (PSR-3) e cache (PSR-16) próprios, implementando as interfaces PSR para manter a interoperabilidade; as mensagens HTTP PSR-7 vêm do nyholm/psr7, e router, ORM e engine de templates também são implementações próprias. Os controllers declaram rotas, middlewares e DTOs validados com atributos do PHP. Em produção, configuração, rotas e container são compilados em arquivos PHP, e a aplicação pode rodar em worker mode no FrankenPHP.',
            'stack' => ['PHP 8.4', 'PSR-7/11/14/15', 'nyholm/psr7', 'symfony/console', 'PDO', 'FrankenPHP', 'Pest', 'PHPStan', 'GitHub Actions'],
            'highlights' => [
                'Router une as rotas dinâmicas de cada método em blocos de regex com marcadores (*:N); um preg_match testa cada bloco.',
                'Container PSR-11 com autowiring, detecção de ciclos e fábricas compiladas em PHP que substituem a reflection em produção.',
                'DTOs hidratados do corpo ou da query com #[FromBody]/#[FromQuery] e validados por atributos, com 422 e erros por campo.',
                'ORM Data Mapper por atributos, com HasMany/BelongsTo carregados em uma única consulta por relação (eager loading).',
                'Worker mode do FrankenPHP que reseta serviços entre requisições e desfaz transações esquecidas na conexão.',
                'Middlewares de sessão (descarta IDs desconhecidos), CSRF com hash_equals, CORS e rate limit com contador em cache PSR-16.',
                'CI com Pint, Rector, PHPStan nível max e 265 testes Pest, além dos testes do skeleton e da app de demonstração.',
            ],
            'endpoints_title' => 'Endpoints da app de demonstração',
            'endpoints' => [
                ['GET', '/api/projects', 'Lista projetos com as tarefas (eager loading) na app demo'],
                ['POST', '/api/projects', 'Cria projeto validado por DTO; nome duplicado retorna 409'],
                ['GET', '/api/tasks', 'Lista tarefas paginadas com filtros de status e projeto'],
                ['POST', '/api/tasks', 'Cria tarefa validada por DTO e retorna 201 com Location'],
                ['GET', '/api/tasks/{id}', 'Detalha a tarefa com o projeto; id inexistente ou não inteiro retorna 404'],
                ['PATCH', '/api/tasks/{id}', 'Atualização parcial; concluir dispara o evento TaskCompleted'],
                ['DELETE', '/api/tasks/{id}', 'Remove a tarefa e retorna 204'],
                ['POST', '/tasks', 'Cria tarefa pelo formulário do quadro web, com CSRF e mensagem flash'],
            ],
            'flow' => [
                ['public/index.php', 'Front controller que chama Application::run()'],
                ['Foundation/Application', 'Carrega .env/config, providers e cria a requisição PSR-7'],
                ['Http/Kernel + Pipeline', 'Middlewares globais PSR-15 de config/http.php (erros, sessão, CSRF)'],
                ['Routing/RouteHandler + Router', 'Casa a rota (404/405) e aplica middlewares da rota'],
                ['Routing/ControllerInvoker', 'Autowiring, conversão de parâmetros e DTOs validados'],
                ['Http/ResponseFactory', 'Converte o retorno do controller em resposta'],
                ['Http/Emitter/SapiEmitter', 'Emite headers, status e corpo em blocos'],
            ],
        ],

        [
            'slug' => 'tenantly',
            'name' => 'Tenantly',
            'repo' => 'tenantly',
            'language' => 'PHP',
            'category' => 'php',
            'date' => '2026-10',
            'featured' => false,
            'summary' => 'Base de SaaS multi-tenant em Laravel 13 e PostgreSQL 17, com papéis de banco separados como preparação para isolamento via RLS.',
            'description' => 'Projeto de SaaS multi-tenant em Laravel cujo princípio, segundo o README, é deixar o isolamento entre tenants a cargo da infraestrutura (scopes globais, Row Level Security no Postgres e testes automáticos), para que esquecer um where não vaze dados. Nesta etapa inicial existe só a fundação: o Postgres separa o papel dono do schema, o papel da aplicação sem BYPASSRLS e um papel administrativo, e migrations, testes e CI já respeitam essa separação.',
            'stack' => ['PHP 8.4', 'Laravel 13', 'PostgreSQL 17', 'Redis 7', 'Octane (FrankenPHP)', 'Pest', 'Larastan', 'Docker', 'GitHub Actions'],
            'highlights' => [
                'Três papéis no Postgres: migrator dono do schema, app sem BYPASSRLS e admin com BYPASSRLS restrito a DML.',
                'Privilégios padrão dão a app e admin só SELECT, INSERT, UPDATE e DELETE nas tabelas que o migrator criar.',
                'Listener de eventos do Artisan troca a conexão padrão para migrator em migrate:*, db:seed, db:wipe e schema:dump.',
                'Testes migram com o papel dono do schema e executam com o papel da aplicação, sem BYPASSRLS, como em produção.',
                'Teste de feature garante que a aplicação conecta como tenantly_app, sem BYPASSRLS e sem superusuário.',
                'CI no GitHub Actions com Pint, Larastan em nível máximo e Pest contra serviços Postgres 17 e Redis 7.',
            ],
            'flow_title' => 'Provisionamento do banco',
            'flow' => [
                ['initdb/10-tenantly.sh', 'Dispara o setup na primeira subida do volume'],
                ['postgres/setup.sh', 'Cria papéis e bancos (dev e teste)'],
                ['roles.sql', 'Define migrator, app (sem BYPASSRLS) e admin'],
                ['database.sql', 'Revoga PUBLIC e concede só DML a app e admin'],
                ['config/database.php', 'Conexões pgsql, pgsql_admin e migrator'],
                ['UseMigratorConnectionForSchemaCommands', 'Comandos de schema usam o papel dono'],
                ['RefreshDatabaseAsMigrator', 'Migra como migrator e testa como app'],
            ],
        ],

        [
            'slug' => 'gestao-de-viacoes',
            'name' => 'Sistema de Gestão de Viações',
            'repo' => 'MVC_site',
            'language' => 'PHP',
            'category' => 'php',
            'date' => '2026-04',
            'featured' => true,
            'stars' => 1,
            'forks' => 1,
            'summary' => 'Aplicação web em PHP 8.4 com Clean Architecture, painel administrativo protegido e auditoria imutável.',
            'description' => 'Sistema para centralizar a gestão de empresas de transporte, construído do zero sem framework. Segue princípios de arquitetura defensiva: ambiente 100% replicável via Docker, proteção contra as principais vulnerabilidades da OWASP e um histórico de auditoria que preserva a integridade dos dados mesmo após exclusões.',
            'stack' => ['PHP 8.4', 'MVC', 'Clean Architecture', 'PDO', 'MySQL', 'Docker', 'PHPUnit'],
            'highlights' => [
                'Rate limiting anti-brute force com bloqueio temporário após tentativas de login falhas.',
                'Proteção CSRF com tokens dinâmicos validados via hash_equals em POST, PUT e DELETE.',
                'Security headers (CSP, X-Frame-Options) e defesa em profundidade contra XSS.',
                'Migração automática de hashes legados (Bcrypt) para Argon2id no momento do login.',
                'Upload validado pelos bytes reais do arquivo (MIME), com nomes únicos e limpeza de arquivos órfãos.',
                'Auditoria visual com comparativo de/para e índices no lugar de FKs para preservar o histórico.',
                'Cache em JSON com TTL de 300s e invalidação sincronizada em toda operação de escrita.',
            ],
            'flow' => [
                ['public/index.php', 'Front Controller, sessão e CSRF'],
                ['Core/Router.php', 'Despacho de rotas e method spoofing'],
                ['Controllers', 'Camada fina que empacota DTOs'],
                ['DTOs', 'Objetos imutáveis e tipados'],
                ['Services', 'Regras de negócio e anti-brute force'],
                ['Repositories', 'Persistência via PDO'],
                ['Models', 'Objetos de domínio'],
            ],
        ],

        [
            'slug' => 'api-delivery-laravel',
            'name' => 'API Delivery de Comida',
            'repo' => 'delivery_api_facul',
            'language' => 'PHP',
            'category' => 'php',
            'date' => '2026-06',
            'featured' => true,
            'forks' => 1,
            'summary' => 'API RESTful em Laravel para produtos e pedidos, com cálculo de frete via ViaCEP e testes com PHPUnit.',
            'description' => 'Trabalho final da disciplina de Integração de Sistemas de Software: uma API de delivery construída em Laravel seguindo MVC, com as regras de negócio isoladas em um service. Os dados ficam no cache do Laravel, sem banco relacional, e o endereço de entrega é resolvido automaticamente pela API do ViaCEP.',
            'stack' => ['PHP 8.3', 'Laravel 13', 'ViaCEP', 'PHPUnit', 'Docker'],
            'highlights' => [
                'Regras de negócio isoladas em PedidoService, mantendo os controllers enxutos.',
                'Frete calculado pelo CEP: R$ 5,00 para a mesma cidade e R$ 15,00 para outros municípios.',
                'Endereço completo (logradouro, bairro e cidade) salvo automaticamente no pedido.',
                'Validação antecipada: pedidos sem itens retornam 400 antes de qualquer chamada externa.',
                'Endpoint de eventos que responde 202 Accepted simulando processamento assíncrono.',
                'Testes unitários e de feature com PHPUnit, além de Dockerfile e compose.yaml.',
            ],
            'endpoints' => [
                ['GET', '/produtos', 'Lista os produtos cadastrados'],
                ['POST', '/produtos', 'Cadastra um produto'],
                ['GET', '/pedidos', 'Lista todos os pedidos'],
                ['GET', '/pedidos/{id}', 'Detalha um pedido'],
                ['POST', '/pedidos', 'Cria um pedido calculando o frete via CEP'],
                ['PUT', '/pedidos/{id}/status', 'Atualiza o status de um pedido'],
                ['POST', '/eventos/pedido-confirmado', 'Simula a confirmação (202 Accepted)'],
            ],
        ],

        [
            'slug' => 'gerenciador-de-tarefas-django',
            'name' => 'Sistema de Gerenciamento de Tarefas',
            'repo' => 'Sistema-de-gerenciamento-de-tarefas-web',
            'language' => 'Python',
            'category' => 'python',
            'date' => '2026-09',
            'featured' => true,
            'summary' => 'Aplicação web estilo Trello em Django com autenticação, atribuição de tarefas, status e dashboard do grupo.',
            'description' => 'Gerenciador de tarefas em Django com cadastro e login de usuários, CRUD completo, atribuição de responsáveis e acompanhamento por status. O front-end é feito com templates e CSS puro, e as regras de permissão garantem que apenas o criador ou o responsável alterem uma tarefa.',
            'stack' => ['Python', 'Django 5', 'SQLite', 'HTML', 'CSS'],
            'highlights' => [
                'Cadastro, login e logout com sessões gerenciadas pelo Django.',
                'CRUD de tarefas com página de detalhes, criador e responsável.',
                'Status pendente, em andamento e concluída, com filtros reutilizáveis.',
                'Dashboard do grupo com contadores por status.',
                'Permissões: somente o criador ou o responsável podem editar ou excluir.',
                '24 testes automatizados cobrindo as regras da aplicação.',
            ],
        ],

        [
            'slug' => 'php-task-app-fork',
            'name' => 'PHP Task App — Contribuições',
            'repo' => 'fork-Pfeifer',
            'language' => 'PHP',
            'category' => 'php',
            'date' => '2026-06',
            'featured' => false,
            'summary' => 'Fork de um app PHP com Docker em que adicionei CRUD de usuários, soft delete, histórico unificado e paginação.',
            'description' => 'Contribuição sobre um projeto PHP existente, rodando em Docker com MySQL. O fork amplia o sistema original com gestão completa de usuários e um modelo de histórico único para todas as entidades.',
            'stack' => ['PHP', 'MySQL 8', 'Docker', 'Composer'],
            'highlights' => [
                'CRUD completo de usuários: criação, edição, listagem, visualização e remoção.',
                'Soft delete em usuários e viações, com restauração pela interface.',
                'Tabela unificada de histórico para todas as alterações.',
                'Página individual de cada registro com seu histórico completo.',
                'Paginação e filtros nas listagens.',
            ],
        ],

        [
            'slug' => 'crud-de-viacoes',
            'name' => 'CRUD de Viações',
            'repo' => 'site-php',
            'language' => 'PHP',
            'category' => 'php',
            'date' => '2026-04',
            'featured' => false,
            'summary' => 'CRUD em PHP 8.4 + MySQL com auditoria granular campo a campo, upload seguro e cache em disco.',
            'description' => 'Sistema de gerenciamento de viações com cadastro, edição, exclusão e uma "caixa-preta" de auditoria que registra exatamente o que mudou em cada operação. Roda em containers Docker (Apache + MySQL).',
            'stack' => ['PHP 8.4', 'MySQL 8', 'PDO', 'Docker', 'Composer'],
            'highlights' => [
                'Transações PDO: o registro e o primeiro log são salvos juntos ou nenhum é salvo.',
                'Logs granulares do tipo "Cidade alterada de A para B".',
                'Upload de logos validado por MIME type, com remoção da imagem antiga.',
                'Exclusão protegida via POST e busca dinâmica por nome ou status.',
            ],
        ],

        [
            'slug' => 'it-asset-tracker',
            'name' => 'IT Asset Tracker',
            'repo' => 'ITAssetTracker',
            'language' => 'C#',
            'category' => 'dotnet',
            'date' => '2026-02',
            'featured' => false,
            'summary' => 'API em ASP.NET Core para controle de equipamentos de TI e empréstimos a funcionários.',
            'description' => 'API para inventário de TI: cadastra equipamentos, controla o status de cada um e registra empréstimos e devoluções para funcionários, impedindo que um item indisponível seja emprestado.',
            'stack' => ['C#', 'ASP.NET Core', 'Entity Framework Core', 'SQLite', 'Swagger'],
            'highlights' => [
                'Entidades Equipment, Employee e Assignment com identificadores GUID.',
                'Status do equipamento: disponível, em uso ou em manutenção.',
                'Empréstimo bloqueado quando o equipamento não está disponível.',
                'Devolução com data registrada e status restaurado automaticamente.',
            ],
            'endpoints' => [
                ['GET', '/api/equipments', 'Lista os equipamentos'],
                ['POST', '/api/equipments', 'Cadastra um equipamento'],
                ['POST', '/api/assignments', 'Empresta um equipamento'],
                ['PUT', '/api/assignments/{id}/return', 'Registra a devolução'],
            ],
        ],

        [
            'slug' => 'api-cep-e-clima',
            'name' => 'API de Consumo — CEP e Clima',
            'repo' => 'api-consumo',
            'language' => 'JavaScript',
            'category' => 'js',
            'date' => '2026-04',
            'featured' => false,
            'summary' => 'API REST em Express que integra ViaCEP e wttr.in com respostas padronizadas e tratamento de erros.',
            'description' => 'Serviço em Node.js que consome duas APIs públicas — ViaCEP para endereços e wttr.in para clima — e devolve respostas padronizadas, diferenciando CEP inexistente (404) de CEP mal formatado (400).',
            'stack' => ['Node.js', 'Express', 'ViaCEP', 'wttr.in'],
            'highlights' => [
                'Separação em routes, controllers e services.',
                'Endereço formatado pronto para exibição na resposta.',
                'Respostas de erro consistentes para 400 e 404.',
                'Coleção do Thunder Client versionada para testar os endpoints.',
            ],
            'endpoints' => [
                ['GET', '/cep/{cep}', 'Consulta endereço no ViaCEP'],
                ['GET', '/clima/{cidade}', 'Consulta o clima no wttr.in'],
            ],
        ],

        [
            'slug' => 'delivery-api-express',
            'name' => 'Delivery API — Pizzaria',
            'repo' => 'delivery-api',
            'language' => 'JavaScript',
            'category' => 'js',
            'date' => '2026-04',
            'featured' => false,
            'summary' => 'Sistema de pedidos de pizzaria em Node.js + Express seguindo a arquitetura MVC.',
            'description' => 'API de pedidos com listagem dos pedidos ativos e total geral, criação com validação de dados e cancelamento por status.',
            'stack' => ['Node.js', 'Express', 'MVC'],
            'highlights' => [
                'Total geral calculado apenas sobre pedidos não cancelados.',
                'Validação de dados obrigatórios na criação.',
                'Cancelamento por mudança de status, sem apagar o histórico.',
            ],
        ],

        [
            'slug' => 'api-de-produtos',
            'name' => 'API de Produtos',
            'repo' => 'tarefa-api',
            'language' => 'JavaScript',
            'category' => 'js',
            'date' => '2026-04',
            'featured' => false,
            'summary' => 'API REST de produtos em Express 5 com rotas, controllers e services separados.',
            'description' => 'API de produtos organizada em camadas e testada com uma coleção do Thunder Client.',
            'stack' => ['Node.js', 'Express 5'],
            'highlights' => [
                'Camadas de routes, controllers e services.',
                'Coleção do Thunder Client para testes manuais.',
            ],
        ],

        [
            'slug' => 'calendario-app',
            'name' => 'CalendarioApp',
            'repo' => 'estudar',
            'language' => 'Kotlin',
            'category' => 'mobile',
            'date' => '2025-11',
            'featured' => false,
            'summary' => 'App Android de calendário em Kotlin + Jetpack Compose com MVVM, Navigation e Firestore.',
            'description' => 'Aplicativo de calendário com criação, listagem e detalhes de eventos. Segue a arquitetura recomendada para Android: telas em Compose observam um ViewModel com StateFlow, que delega o acesso a dados a um repositório conectado ao Firebase Firestore.',
            'stack' => ['Kotlin', 'Jetpack Compose', 'MVVM', 'Firebase'],
            'highlights' => [
                'Telas de calendário, lista de eventos, detalhes, criação e configurações.',
                'ViewModel com StateFlow sobrevivendo a mudanças de configuração.',
                'Repositório isolando o acesso ao Firestore.',
                'Navegação com Navigation Compose.',
            ],
        ],

        [
            'slug' => 'todolist-android',
            'name' => 'ToDoList Android',
            'repo' => 'ToDoList',
            'language' => 'Kotlin',
            'category' => 'mobile',
            'date' => '2025-09',
            'featured' => false,
            'summary' => 'App Android de lista de tarefas com Jetpack Compose e componentes reutilizáveis.',
            'description' => 'Primeiro app Android: lista de tarefas com tela de adição, listagem e componentes de UI reutilizáveis em Compose.',
            'stack' => ['Kotlin', 'Jetpack Compose'],
            'highlights' => [
                'Telas de listagem e adição de tarefas.',
                'Componentes reutilizáveis como caixa de texto e item de lista.',
            ],
        ],

        [
            'slug' => 'catalogo-com-comentarios',
            'name' => 'Catálogo com Comentários',
            'repo' => 'ProvaA1',
            'language' => 'TypeScript',
            'category' => 'js',
            'date' => '2025-06',
            'featured' => false,
            'summary' => 'Front-end em Next.js 15 + TypeScript que consome uma API de itens, categorias e comentários, com login.',
            'description' => 'Interface que lista itens por categoria, mostra detalhes com comentários e permite comentar após autenticação, consumindo a API via Axios.',
            'stack' => ['TypeScript', 'Next.js 15', 'React 19', 'Axios'],
            'highlights' => [
                'Tipagem das entidades Item, Categoria, Usuário e Comentário.',
                'Rotas dinâmicas para detalhes do item.',
                'Componentes de formulário e listagem de comentários.',
            ],
        ],

        [
            'slug' => 'explorador-de-paises',
            'name' => 'Explorador de Países',
            'repo' => 'revisao_paises_front',
            'language' => 'TypeScript',
            'category' => 'js',
            'date' => '2025-06',
            'featured' => false,
            'summary' => 'Next.js consumindo a REST Countries API com listagem e página de detalhes por código.',
            'description' => 'Aplicação em Next.js que lista países a partir da REST Countries API e exibe os detalhes de cada um em uma rota dinâmica.',
            'stack' => ['TypeScript', 'Next.js 15', 'Axios', 'REST Countries'],
            'highlights' => [
                'Listagem de países consumindo API pública.',
                'Rota dinâmica de detalhes por código do país.',
            ],
        ],

        [
            'slug' => 'painel-de-produtos',
            'name' => 'Painel de Produtos',
            'repo' => 'f',
            'language' => 'TypeScript',
            'category' => 'js',
            'date' => '2025-06',
            'featured' => false,
            'summary' => 'Front-end Next.js com login de usuário e listagem de produtos integrado a uma API .NET.',
            'description' => 'Front-end em Next.js com páginas de login e listagem de produtos, tipado com as mesmas entidades da API de usuários e produtos.',
            'stack' => ['TypeScript', 'Next.js 15', 'Axios'],
            'highlights' => [
                'Tipos de Usuário, Produto e Permissão compartilhados com a API.',
                'Páginas de login e listagem com App Router.',
            ],
        ],

        [
            'slug' => 'api-usuarios-e-produtos',
            'name' => 'API de Usuários e Produtos',
            'repo' => 'novo',
            'language' => 'C#',
            'category' => 'dotnet',
            'date' => '2025-06',
            'featured' => false,
            'summary' => 'API ASP.NET Core com EF Core, repositórios e controle de permissões entre usuário e administrador.',
            'description' => 'API com cadastro de usuários e produtos, permissões por perfil e acesso a dados encapsulado em repositórios.',
            'stack' => ['C#', 'ASP.NET Core', 'Entity Framework Core'],
            'highlights' => [
                'Repository pattern com interfaces para usuários e produtos.',
                'Perfis de permissão: usuário e administrador.',
                'Migrations do Entity Framework versionadas.',
            ],
        ],

        [
            'slug' => 'api-streamer',
            'name' => 'API Streamer',
            'repo' => 'API-STREAMER',
            'language' => 'C#',
            'category' => 'dotnet',
            'date' => '2025-05',
            'featured' => false,
            'team' => true,
            'summary' => 'API de catálogo de filmes, categorias e usuários desenvolvida em equipe com ASP.NET Core.',
            'description' => 'Projeto em equipe de uma API para uma plataforma de streaming. Minha contribuição foi o módulo de usuários: controller, repositório, ajustes nos modelos e a migration inicial com MySQL.',
            'stack' => ['C#', 'ASP.NET Core', 'Entity Framework Core', 'MySQL'],
            'highlights' => [
                'Controllers de filmes, categorias e usuários.',
                'Repositórios com interfaces para cada entidade.',
                'Arquivos .http para testar cada recurso.',
            ],
        ],

        [
            'slug' => 'api-de-eventos',
            'name' => 'API de Eventos',
            'repo' => 'ProvaDSV',
            'language' => 'C#',
            'category' => 'dotnet',
            'date' => '2025-05',
            'featured' => false,
            'team' => true,
            'summary' => 'API de eventos e usuários em ASP.NET Core com EF Core, desenvolvida em dupla.',
            'description' => 'API construída em dupla com cadastro de eventos e usuários, repositório para eventos e arquivos .http para testar as rotas.',
            'stack' => ['C#', 'ASP.NET Core', 'Entity Framework Core'],
            'highlights' => [
                'Controllers de eventos e usuários.',
                'Repository pattern para eventos.',
                'Migrations e arquivos .http para testes.',
            ],
        ],

        [
            'slug' => 'sistemas-criticos-com-padroes',
            'name' => 'Sistemas Críticos com Padrões GoF',
            'repo' => 'prova2',
            'language' => 'Java',
            'category' => 'java',
            'date' => '2025-11',
            'featured' => false,
            'summary' => 'Quatro sistemas — risco financeiro, banco legado, usina e NF-e — resolvidos com Strategy, Adapter, State e Chain.',
            'description' => 'Avaliação com quatro cenários de domínio complexo, cada um com um documento de decisões de design justificando o padrão escolhido e os princípios SOLID aplicados.',
            'stack' => ['Java', 'Strategy', 'Adapter', 'State', 'Chain of Responsibility', 'Command'],
            'highlights' => [
                'Strategy para cálculo de risco: VaR, Expected Shortfall e Stress Testing.',
                'Adapter integrando um sistema bancário legado a uma resposta moderna.',
                'State para uma usina com seis estados e bloqueio de transições perigosas.',
                'Chain of Responsibility + Command para validação de NF-e.',
            ],
        ],

        [
            'slug' => 'adapter-midias-sociais',
            'name' => 'Integração de Mídias Sociais',
            'repo' => 'Adapter',
            'language' => 'Java',
            'category' => 'java',
            'date' => '2025-10',
            'featured' => false,
            'summary' => 'Padrão Adapter unificando a publicação em Twitter, Instagram, LinkedIn e TikTok.',
            'description' => 'Sistema para uma agência de marketing publicar em várias redes através de uma única interface, mesmo com APIs de assinaturas diferentes.',
            'stack' => ['Java', 'Adapter'],
            'highlights' => [
                'Interface alvo ConectorMidiaSocial com um único método publicar().',
                'Um adapter para cada API simulada.',
            ],
        ],

        [
            'slug' => 'chain-processamento-de-logs',
            'name' => 'Processamento de Logs',
            'repo' => 'Chain',
            'language' => 'Java',
            'category' => 'java',
            'date' => '2025-11',
            'featured' => false,
            'summary' => 'Chain of Responsibility encaminhando logs DEBUG, INFO, WARNING e ERROR para destinos diferentes.',
            'description' => 'Cada handler processa um nível de log: console, memória, arquivo ou simulação de e-mail.',
            'stack' => ['Java', 'Chain of Responsibility'],
            'highlights' => [
                'Handler base para encadeamento.',
                'WARNING gravado em arquivo e ERROR com envio de e-mail simulado.',
            ],
        ],

        [
            'slug' => 'state-gestao-de-pedidos',
            'name' => 'Gestão de Pedidos',
            'repo' => 'State',
            'language' => 'Java',
            'category' => 'java',
            'date' => '2025-10',
            'featured' => false,
            'summary' => 'Padrão State controlando o ciclo de vida de um pedido: novo, pago, enviado, entregue ou cancelado.',
            'description' => 'Cada estado do pedido é uma classe com seu próprio comportamento, eliminando condicionais espalhadas.',
            'stack' => ['Java', 'State'],
            'highlights' => [
                'Cinco estados encapsulados em classes próprias.',
                'Transições válidas definidas por cada estado.',
            ],
        ],

        [
            'slug' => 'strategy-rpg',
            'name' => 'RPG com Strategy',
            'repo' => 'Strategy',
            'language' => 'Java',
            'category' => 'java',
            'date' => '2025-10',
            'featured' => false,
            'summary' => 'Personagens de RPG que trocam armas e efeitos de status em tempo de execução com o padrão Strategy.',
            'description' => 'Guerreiro, Mago, Arqueiro e Paladino combinam armas e efeitos (queimadura, sangramento, atordoamento) como estratégias intercambiáveis.',
            'stack' => ['Java', 'Strategy'],
            'highlights' => [
                'Armas e efeitos como estratégias intercambiáveis.',
                'Classe base de efeitos para reaproveitar comportamento.',
            ],
        ],

        [
            'slug' => 'factory-e-strategy',
            'name' => 'Relatórios e Investimentos',
            'repo' => 'provasemestre',
            'language' => 'Java',
            'category' => 'java',
            'date' => '2025-11',
            'featured' => false,
            'summary' => 'Factory Method para relatórios de logística e Strategy para perfis de risco de investimento.',
            'description' => 'Duas questões de avaliação: fábricas de relatórios diário, semanal e emergencial, e modelos conservador, moderado e agressivo para análise de clientes.',
            'stack' => ['Java', 'Factory Method', 'Strategy'],
            'highlights' => [
                'Uma fábrica concreta para cada tipo de relatório.',
                'Modelos de risco intercambiáveis na plataforma de investimentos.',
            ],
        ],

        [
            'slug' => 'observer-decorator-factory',
            'name' => 'Observer, Decorator e Factory',
            'repo' => 'Prova-Projeto',
            'language' => 'Java',
            'category' => 'java',
            'date' => '2025-10',
            'featured' => false,
            'team' => true,
            'summary' => 'Avaliação em grupo com notícias (Observer), relatórios (Decorator) e pagamentos e transportes (Factory).',
            'description' => 'Projeto em grupo no qual fui o principal autor de commits: cada tarefa aplica um padrão diferente a um domínio próprio.',
            'stack' => ['Java', 'Observer', 'Decorator', 'Factory Method'],
            'highlights' => [
                'Site de notícias notificando leitores com Observer.',
                'Relatórios com PDF, gráficos e estatísticas via Decorator.',
                'Pagamentos (Pix, boleto, cartão) e transportes criados por fábricas.',
            ],
        ],

        [
            'slug' => 'factory-pagamentos',
            'name' => 'Pagamentos com Factory Method',
            'repo' => 'Tarefa1',
            'language' => 'Java',
            'category' => 'java',
            'date' => '2025-09',
            'featured' => false,
            'summary' => 'Cartão de crédito, PayPal e criptomoeda criados por fábricas específicas.',
            'description' => 'Serviço de pagamentos que desconhece as classes concretas, delegando a criação a fábricas.',
            'stack' => ['Java', 'Factory Method'],
            'highlights' => [
                'Uma fábrica por meio de pagamento.',
                'Service desacoplado das implementações concretas.',
            ],
        ],

        [
            'slug' => 'singleton-contas',
            'name' => 'Gerenciador de Contas',
            'repo' => 'Tarefa',
            'language' => 'Java',
            'category' => 'java',
            'date' => '2025-09',
            'featured' => false,
            'summary' => 'Singleton garantindo uma única instância do gerenciador de contas com depósitos e saques.',
            'description' => 'AccountManager com construtor privado e acesso global controlado por getInstance().',
            'stack' => ['Java', 'Singleton'],
            'highlights' => [
                'Instância única com inicialização preguiçosa.',
                'Saque validado contra o saldo disponível.',
            ],
        ],

        [
            'slug' => 'biblioteca-poo',
            'name' => 'Sistema de Biblioteca',
            'repo' => 'Tarefa-2',
            'language' => 'Java',
            'category' => 'java',
            'date' => '2025-09',
            'featured' => false,
            'summary' => 'Livros, revistas e mídias digitais modelados com herança, interfaces e polimorfismo.',
            'description' => 'Exercício de orientação a objetos com uma classe base de item de biblioteca e a interface Borrowable.',
            'stack' => ['Java', 'POO'],
            'highlights' => [
                'Hierarquia LibraryItem → Book, Magazine e DigitalMedia.',
                'Interface Borrowable para itens emprestáveis.',
            ],
        ],

    ],

];
